name: Sync to Hugging Face hub
on:
  push:
    branches: [deployment]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: deployment
          sparse-checkout: |
            src
            app.py
            requirements.txt
          sparse-checkout-cone-mode: false
          fetch-depth: 0
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Create commit
        env:
            HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run : |
          mkdir -p push-hf-dir
          mv src app.py requirements push-hf-dir
          cd push-hf-dir
          git init --initial-branch=main
          git add .
          git commit -m "Changes from 'https://github.com/ggruber193/pubmed-central-semantic-search'"
          git pull
          git push --force https://yeastcoast:$HF_TOKEN@huggingface.co/spaces/yeastcoast/pubmed-central-semantic-search main
          
