name: Sync to Hugging Face hub
on:
  push:
    branches: [deployment]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src
            app.py
          sparse-checkout-cone-mode: false
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://yeastcoast:$HF_TOKEN@huggingface.co/spaces/yeastcoast/pubmed-central-semantic-search main
